# Generated by Django 6.0.7 on 2026-07-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cake_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='custom_cakes/'),
        ),
    ]
